docksal/docksal

README.md, bin/fin, docs/apache-solr.md, docs/db-access.md, docs/docksal-stack.md, docs/docksal-volumes.md, docs/env-setup-native.md, docs/project-customize.md, docs/project-setup.md, docs/update-dde.md, examples/.docksal/docksal.yml, stacks/services.yml, stacks/stack-acquia-static.yml, stacks/stack-acquia.yml, stacks/stack-default-static.yml, stacks/stack-default.yml, stacks/volumes-bind.yml, stacks/volumes-nfs.yml, stacks/volumes-unison.yml
- Switched to Docker Compose v1.9 and updated config files to compose file format v2.1
- Enabled project volumes provisioning by default. Experimental, but does not break anything for any existing projects. Used in docksal/drupal8
- `fin generate --static` to generate a standalone project stack config, which will not be updated with a new version of Docksal
- Documentation updates
=> Volumes, configuration and docs updates

examples/.docksal/docksal.yml
Just a spelling mistake in the example `docksal.yml` file
stiches -> stitches
=> Correct typo: stiches

bin/fin
to be able to avoid port conflicts with already running apache or nginx server.
=> Allow another port for vhost-proxy service

docs/multiple-projects.md
Just a simple typo I found when browsing the documentation.
=> Correct documentation typos: multiple projects page

docs/custom_theme/searchbox.html, mkdocs.yml
Issue: search is not working at http://docksal.readthedocs.io
Steps to reproduce the issues:
* open http://docksal.readthedocs.io
* try to search for something, e.g. "zero" (I was looking for instructions for zero configuration setup)
Expected result:
* search results should be shown (as I know that zero configuration setup is documented)
Current result::
* nothing found
* search url looks like: https://readthedocs.org/search/?q=zero&check_keywords=yes&area=default&project=docksal&version=master&type=file
After some research I found these threads below and that workaround is to change the search result URL to, e.g. http://docksal.readthedocs.io/en/master/search.html?q=zero
Referenced issues:
https://github.com/rtfd/readthedocs.org/issues/1487 …
=> Docs: workaround for search not working see rtfd/readthedocs.org#1088

bin/fin
Not needed at all for dns and ssh-agent and no longer needed for vhost-proxy.
vhost-proxy tests are passing after this change:
https://travis-ci.org/docksal/service-vhost-proxy/builds/208639080
=> Remove --privileged --userns=host from system services (closes #138)

bin/fin, stacks/services.yml, tests/smoke-test-cli-tools.bats, tests/smoke-test-duplicates.bats, tests/smoke-test-general.bats
This new commands allows running a command in a standalone cli container (outside of any project). The current directory on the host is mapped to /var/www inside the container.
Host user uid/gid are mapped during container startup. This is now handled by the cli container itself: https://github.com/docksal/service-cli/commit/857a91d77d10ca20ded7a7006270e293a7d2ef87
Backward compatibility is preserved - fin will still run _set_cli_uid() when starting a project stack.
=> fin run-cli

bin/fin
Portable support for:
- update_virtualbox
- install_tools_mac
- install_tools_windows
This also works with the new get.docksal.io installer.
Fin and stack files are still downloaded from internet, but everything else (VirtualBox, boot2docke.iso, tools, Docksal system images) supports local copies from the directory where the installer in launched.
Mac - http://take.ms/7I3jo
Windows - http://take.ms/mLcjm
=> Portable support

bin/fin
This will fix #200, where VirtualBox installer path was passed to cmd.exe in Linux format instead of Windows.
=> Fix #200 - VBox installer path on Windows

bin/fin
This should address several situations discovered in #117.
- Create and use shares using unique names: `docksal-c`, `docksal-d`, etc. (avoid conflicts with existing shares (`c`, `d`, etc.) a user may have)
- Specify the user domain when mounting (should help with domain users)
- Perform two attempts to mount a SMB share: use ntlmssp by default, use ntlm as a fallback
- Allow overriding sec option via SEC_SMB. Useful for debugging, e.g. `SMB_SEC=ntlmv2 fin debug docker_machine_mount_smb`
=> Windows SMB share/mount refactoring. Fixes #117

bin/fin, docs/advanced/dns-resolver.md, docs/advanced/multiple-projects.md, docs/advanced/stack.md, mkdocs.yml
- Refactoring DNS settings
- Doing a DNS probe to make sure the upstream DNS server is reachable
- Using 8.8.8.8 a the default upstream DNS on all platforms
- Allow disabling the automatic DNS resolver via `DOCKSAL_NO_DNS_RESOLVER=true
- Set interface metric on Windows
- This makes sure our VBox adapters is the first in the list and thus it's DNS server settings will be used by Windows
- Adding configure_resolver "off" mode
- This will revert resolver settings when the VM is stopped, killed, removed
- Update docs regarding the DNS resolver
=> DNS resolver refactoring. Fixes #242

bin/fin
Requires docksal/cli version edge (or 1.3.0+ eventually). Falls back to `sleep 5` for older versions.
=> Replace sleep with a true healthcheck for cli. Fixes #225

bin/fin, docs/advanced/stack-config.md, docs/getting-started/project-setup.md, examples/.docksal/docksal.yml, stacks/services.yml, stacks/stack-acquia-static.yml, stacks/stack-default-static.yml, stacks/volumes-bind.yml, stacks/volumes-nfs.yml, stacks/volumes-unison.yml
Removes dependency on the host's $HOME directory mount.
Keys are copied into the `docksal-ssh-agent` container with `docker cp`, loaded into the ssh-agent, then removed from the container.
=> SSH agent refactoring. Fixes #223

bin/fin
Sometimes it is nice to see which virtual hosts are registered in docksal proxy, especially when you have added mailhog or phpadmin services.
- First commit adds the vhosts command.
- Second commit lists all vhosts after ```up``` and ```start``` commands.
=> Add vhosts command

bin/fin, stacks/services.yml, stacks/stack-acquia-static.yml, stacks/stack-acquia.yml, stacks/stack-default-static.yml
- 1.31.0 Set host IP alias for Docker for Mac/Win
- xdebug settings adjustment for cli
- Point xdebug to the host IP
- Also set `PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}` - this helps with debugging console PHP applications (as per our own docs).
These settings, being set via env variables, take precedence over settings in php.ini.
Long term this will be include in the cli image.
=> Host IP alias on Docker for Mac/Win and xdebug adjustments. Fixes #389

bin/fin, docs/advanced/volumes.md, docs/getting-started/env-setup-native.md, stacks/overrides-osxfs.yml
- This will automatically enabled osxfs:cached mode for the project root volume in cli
- The volume has to be defined using the host path. The cached flag cannot yet be used with named volumes. See https://github.com/docker/for-mac/issues/1899
- Docker Compose update in necessary due to a bug older versions have with merging same volume definitions from multiple yml files
=> Enable osxfs:cached automatically on Docker for Mac. Fixes #249

bin/fin
Starting from Ubuntu 17.04 ifup/ifdown are not available out of the box.
=> Install ifup/ifdown if they are missing. Relates to #321

CHANGELOG.md, bin/fin, docs/advanced/db-import.md, docs/advanced/db-sandbox.md, docs/advanced/extend-images.md, docs/advanced/multiple-projects.md, docs/advanced/networking.md, docs/advanced/ssh-agent.md, docs/advanced/stack-config.md, docs/advanced/stack-settings.md, docs/advanced/vm.md, docs/advanced/volumes.md, docs/advanced/web-http-auth.md, docs/getting-started/project-setup.md, docs/getting-started/setup.md, docs/tools/apache-solr.md, docs/tools/behat.md, docs/tools/blackfire.md, docs/tools/mailhog.md, docs/tools/memcached.md, docs/tools/varnish.md, docs/tools/xdebug.md, docs/troubleshooting.md
From now on the default way to launch commands against project is via `fin project` commands subset. E.g. `fin project start` or `fin p start`.
Old shorthands like `fin start` still work for legacy compatibility.
That's how new help will look
```
$ fin
Docksal Fin v1.40.0 commands:	
project <command>        	Project commands: start, stop, status and more... (fin help project)
vm <command>             	VM commands: start, stop, restart and more... (fin help vm)
db <command>             	DB commands: import, dump, list, cli (fin help db)
bash [service]           	Open shell into service's container. Defaults to cli
logs [service]           	Show service logs (e.g. Apache logs, MySQL logs)
exec <command|file>      	Execute a command or a script in cli
config [command]         	Show or …
```
=> 1.40.0. Enrich <project> commands subset.

bin/fin, docs/advanced/dns-resolver.md, docs/fin/fin.md, docs/getting-started/env-setup-native.md, docs/getting-started/setup.md, tests/smoke-test-system.bats
Initial pass on `fin system` group of commands. Fixes #387 
The goal is to have a clear and clean way of turning everything related to Docksal ON or OFF. The only exclusion would be Docker itself, when run natively (Linux, Docker for Mac/Win).
```
$ fin help system
Manage Docksal
fin system <command> [params]	
Commands:
reset                    	Reset Docksal
start                    	Start Docksal
stop                     	Stop Docksal
status                   	Check Docksal status
Examples:
fin system reset         	Reset all Docksal system services and settings
fin system reset dns     	Reset Docksal DNS service
fin system reset vhost-proxy	Reset Docksal HTTP/HTTPS reverse proxy service (resolves *.docksal domain names into container IPs)
fin system reset ssh-agent	Reset Docksal …
```
=> fin system. Fixes #387

docs/advanced/stack-config.md
Just a simple documentation typo: `dosksal.yml`
=> Fix typo in advanced stack config docs: dosksal

bin/fin
Currently if one has an alias and they want to update it it must be first removed then added again. This pull request makes it possible to update a existing alias by using the normal fin alias creation command. A fin alias update command could have been created but for the limited number of times it would be used it make more sense to have this as part of the fin alias creation command.
I added the "-f" option to `ln` when creating an new fin alias link. This allow one to use the same command to update aliases vs. the current workflow of first removing the alias then adding it back in with the new path.
```bash
fin alias remove projectname
fin alias ~/docker/projectname projectname
```
```bash
fin alias ~/docker/projectname projectname
```
=> Allow `fin alias` creation command to also update aliases

bin/fin
There were quotes missing around the input argument for ${pipe_cmd} causing `db import` to fail if the provided path argument contains spaces.
=> Fix db import for paths with spaces in their name

bin/fin
I added the environmental variable `DOCKSAL_DNS_DOMAIN` to the `fin project create` command so it will be used if set. Formerly `DOCKSAL_DNS_DOMAIN` was ignore upon new project creation
=> Added environmental variable DOCKSAL_DNS_DOMAIN to "fin project create"

bin/fin
The release of docker compose version 1.21.1 added support for dashes and underscores in the project name.
When updating the `COMPOSE_PROJECT_NAME_SAFE` variable differs from the name docker-compose uses.
See commit : https://github.com/docker/compose/commit/5fe3aff1c310d6b8684404b19a8246736cfe8f1a#diff-a04be36073678de95917341f90c2cf58
This change updates the name normalization to match the 1.21.1 version of docker-compose.
=> Allow dash and underscore in docker compose project name.

bin/fin, docs/fin/fin.md
Add an example to `fin db` for importing an gzipped database.
=> Add archived DB import example

bin/fin
Currently after running `fin up` at the end we see the contents of $VIRTUAL_HOST printed to the screen, but this is not a link adding **http://** before the variable output will make this a clickable link on GUI terminals that can then be easily opened.
I added **http://** before the $VIRTUAL_HOST output in terminal for `fin up`. This makes it a link that is clickable. Normally by using **Ctrl-click** or **right-click** to bring up a context sensitive menu.
Not a link.
Clickable link that is underlined on mouse over and right-click give context sensitive menu with options **Open Link** and **Copy Link Address**.
=> Turn $VIRTUAL_HOST output in terminal into link for "fin up"

bin/fin, tests/smoke-test-general.bats
Added in ability for run-cli command to accept docker -e variables.
The purpose for this is that by default variables like `SECRET_TERMINUS_TOKEN` are not passed to the container nor are there currently an easy way to pass them to the `run-cli` container. Additionally, if there are custom images that are use it may be necessary to pass on those environmental variables.
Example use case now:
```
SECRET_TERMINUS_TOKEN=xxx;
fin run-cli -T -e SECRET_TERMINUS_TOKEN=$SECRET_TERMINUS_TOKEN 'terminus sites --fields="id,name,framework" --format=csv';
```
This will allow for us to automatically login to terminus (which when the variable is presented automatically does) and then run any necessary commands through the run-cli command.
=> Adding Environment Variables to run-cli command

docs/fin/addons.md, mkdocs.yml
Added documentation for Addons this should satisfy #524 which asks for documentation for the addons.
I placed the command in the same structure as the Custom Commands and within the `fin` command as I figured that is most likely the best place for that to go.
=> Addon docs

bin/fin, docs/tools/ngrok.md
Extending NGROK so that it utilizes the docker environment variables for authentication.
Environmental variables are outlined on the README within the [repo](https://github.com/wernight/docker-ngrok#environment-variables)
Particularly this is useful if someone has an NGROK account and wants to authenticate using that.
=> Extending NGROK to use Variables

bin/fin
Exporting the DOCROOT variable on fin config generate as it may not be the standard docroot folder.
When running `DOCROOT=web fin config generate` within a project it doesn't include the DOCROOT within `docksal.yml` when the DOCROOT folder is not named `docroot`.
=> Included DOCROOT on config generate

bin/fin
This adds basic support/compatibility with Alpine Linux / PWD (Play-with-Docker)
- workarounds necessary for Alpine/PWD: older Docker version, root user treatment, `docker-compose` installation via PIP
- network configuration for Alpine
- split network and resolver configuration for Ubuntu
- some other refactoring
1. Launch a single node instance on PWD (https://labs.play-with-docker.com/)
2. Install Docksal (currently using a feature branch version), create a non-root user (`docker`)
```
curl -L get.docksal.io | CI=true DOCKSAL_VERSION=feature/alpine bash
addgroup docker
adduser docker -D -G docker -s /bin/bash
```
3. Clone `docksal/drupal8`, set non-root permissions
```
mkdir projects
cd projects
git clone https://github.com/docksal/drupal8.git
chown -R docker:docker drupal8
cd drupal8 …
```
=> Alpine Linux / PWD support

bin/fin, docs/tools/ngrok.md
When supplying arguments for Ngrok I am getting the following issue:
```
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"ngrok http -authtoken=\\\"XXX\\\"  testdrupal_web_1.testdrupal_default:80\": executable file not found in $PATH".
```
This was due to the following being set in my `docksal.env`
```
NGROK_HOSTNAME="testdrupal.docksal"
NGROK_AUTH="XXX"
```
=> ngrok share fix

bin/fin
Added complementary addition to fin db create as was made to fin db drop. Allows a user to simply use fin db create mydb in a script without having to first call fin db drop.
=> fin db create will not fail if database does exist (#548)

bin/fin
I was receiving the message in fin 1.59.0 "Running in a non-interactive environment. SSH keys with passphrases cannot be used." No other non-tty messages were showing. I found that this function was asking if it was in a tty environment but showing a message to the contrary. Just added the ! to the check.
=> Fixed non tty message showing in tty environment

bin/fin
`HOSTS_FILE` path was empty when on WSL in `hosts ()` thus `hosts_add|hosts_remove ()` would fail
=> fixed missing hosts file path on WSL

docs/tools/xdebug.md
Just one more doc update from documentation that was merged this morning. The placement of the word "open" just didn't ready well.
=> Doc update

CHANGELOG.md, bin/fin, docs/fin/fin-run-cli.md, docs/getting-started/env-setup-native.md, docs/tools/drush.md, docs/tools/phpcs.md, docs/tools/redis.md, docs/tools/sass.md
- Fixed an error with setting DB privileges during `fin db create`
- Disabled network cleanup in `fin cleanup` (triggered during updates) (#582)
- Check [this fix](https://github.com/docksal/docksal/issues/582#issuecomment-395537109) if you updated to Docksal 1.9.0 and had your stopped project(s) broken
- Updated 1.9.0 release notes to mention a breaking change in docker-compose 1.21.1
- Fixed typos here and there
=> Release 1.9.1

bin/fin
This adds basic support for Katacoda environments.
Katacoda can be used to build interactive tutorials. Here's a Docksal 101 tutorial example:
https://www.katacoda.com/lmakarov/scenarios/docksal-101
Source: https://github.com/docksal/katacoda-tutorials/tree/master/docksal-101
=> Katacoda environment support

README.md, bin/fin, docs/getting-started/project-setup.md, docs/index.md, docs/tools/xdebug.md, docs/troubleshooting-smb.md, docs/troubleshooting.md, tests/smoke-test-config.bats
Added option for `fin config set/remove` to pass an `--env` flag.
Example of command
```
$ fin config set --env=local TEST=1
Added value for TEST into HOME/.docksal/docksal.env
```
Additionally added tests and updated help command to reflect the changes.
Solves #584
=> added env option for fin config set/remove

bin/fin
In #526 are the find commands changed. At least in Ubuntu I don't see my Custom commands since fin v1.90.
In [find manpage](http://man7.org/linux/man-pages/man1/find.1.html) I find the text:
> -perm +mode
>              This is no longer supported (and has been deprecated since
>              2005).  Use -perm /mode instead.
The idea is to list only executable commands. I have opted to use -executable instead of -perm.
=> Hotfix: fin help doesn't show Custom commands anymore

bin/fin, tests/smoke-test-general.bats
Add ability for containers to use `--container` option when running `fin exec`
Solves https://github.com/docksal/docksal/issues/609
=> Allow for Container Names option with fin exec [WIP]

bin/fin, tests/smoke-test-general.bats
Currently when running `fin run-cli` it doesn't mount the ssh-agent therefore if you have ssh keys that are used for private git repos then they aren't included and you are prompted with a password for 
```
Enter passphrase for key '/home/docker/.ssh/id_rsa':
```
This is important if we want to try and convince people to use `run-cli` for things like using `terminus` or `npm` other mechanisms that require public key authentication.
=> Added docksal_ssh_agent to volumes for run-cli

docs/advanced/cron.md, mkdocs.yml
* Added command to run crontab commands within the `cli` container.
* Added docs for configuring `crontab` file within project.
**Pending PR https://github.com/docksal/service-cli/pull/64**
Solves https://github.com/docksal/docksal/issues/238
=> Cron Docs and Command

stacks/services.yml, stacks/volumes-bind.yml, stacks/volumes-nfs.yml, stacks/volumes-unison.yml
This gives database data volumes a name - `db_data`. This way they are easy to identify in the list of volumes (docker volume ls). E.g., `drupal8_db_data` vs `dd035157ff4f8ab90e60ece910c335c561caae6325382dc31435de56c0380346`
=> Named db_data volume for MySQL/PostreSQL

bin/fin
- `bash -l` makes sure `~/.profile` is sources inside cli (for both interactive and non-interactive sessions)
- Dropped .docksalrc. It was necessary for older drush versions, which were bash aliases in previous docksal/cli versions (up until v2.1.0).
=> Switched to using bash login sessions for cli (bash -l)

examples/.docksal/commands/phpcs
Updated phpcs command to include coding standards of DrupalPractice and Drupal standard.
Closes #724
=> Updated phpcs command

bin/fin
`fin help` console output
Before:
After:
=> Fix help for project/global commands on Ubuntu 18.04.

docs/advanced/cron.md
Seems typo in the docs.
Relates issue: #671
=> Fix path in cron docs

bin/fin
The comments said that the first suitable nameserver is used, but it actually took the _last_ suitable nameserver in `resolv.conf`. This PR fixes that behavior.
=> Fix detecting first nameserver in resolv.conf

bin/fin, docs/tools/blackfire.md, stacks/services.yml
Treat Blackfire keys as secrets without using the `SECRET_` prefix. See https://github.com/docksal/docksal/pull/783#issuecomment-415080823 for details.
This replaces #783.
=> Handle Blackfire secrets as a special case. Closes #783

bin/fin
This PR changes the behavior of the command `fin reset db`. The usage string in the command line says `fin reset` does this:
reset [service]            Recreate all or specified project services, their containers and named volumes
Changes to home directory in `cli` are preserved.
So I expect `fin reset db` to throw away the database volumes. Instead, what it currently does is keep the volume so the only easy way to get rid of them is to reset your entire project. The reason it works this way this is that it used `docker-compose rm -v` to remove the volumes, but the DB volume is not anonymous.
I've interpreted this to be a bug and fixed it in this pull request. In this PR, `fin reset db` does what it previously did, and also removes the database volume.
If there are any questions or …
=> Drop volume when resetting db container

bin/fin
This prevents broken system states where one or more Docksal services failed to
start without the user being informed of this being the case.
Examples of causes:
- Network issues
- Providing the wrong image name for the system services
Fixes #772.
=> Exit if system services failed to start

stacks/volumes-unison.yml
Updates the volumes-unison settings to default to SYNC_PREFER=newer
This sets the option to sync the most recently changed files when a change conflict occurs.
fixes docksal/unison/issues/2
=> sets default SYNC_PREFER to newer to prefer most recently updated files

bin/fin, docs/content/fin/custom-commands.md, tests/general.bats
Remove an ability for addons to use target run-cli. (Fixes #771)
+ Also sync Unison changes from develop
=> Remove an ability for addons to use target run-cli

bin/fin
`${var^^}` transformations are available in Bash 4, while macOS still ships with Bash 3. Doh...
Removed uppercase transformation in `fin ssh-key add`. This was not even necessary.
Fixes #855
=> Fixed "fin ssh-key add <key-name>" compatibility with Bash 3. Fixes #855

bin/fin
line 2960 adds  --depth=1 to git clone command to clone project boilerplate repos with only a single depth.
Additionally, I included very minor typo fixes in fin comments (commas, spelling typos, etc).
=> shallow clone

docs/content/tools/drupal-contribution.md
Here's an attempt to document the core contribution boilerplate mentioned in #818.
I put it in the _Tools and integrations_ section.
As I said there, I'm happy to turn that repository over to the `docksal` organization if there is broader interest in maintaining it.
=> Documents the core contribution boilerplate.

bin/fin
"docker network inspect" does not list inactive endpoints (stopped containers), so cannot be used to list all containers attached to a network.
Instead, we'll assume we should disconnect all project containers + vhost-proxy from the project network.
Note: this obviously fill fail if some container is manually attached to the project network.
=> Changed the way we get the list of containers in a project network. Fixes #875

bin/fin
When using `ssh-keygen -t ed25519`, a file on the path `~/.ssh/id_ed25519` is created by default. This adds support to Docksal for that default key location.
=> Support default Ed25519 SSH key

bin/fin
Check that certificates folder is mapped into Docker with new function introduced in #657. Fixes #850 
[ Squash merge when merging ]
=> Only mount custom certificates folder to the proxy if it is mapped to Docker (fixes #850)

docs/layouts/partials/menu-footer.html, docs/static/css/theme-docksal.css
This change fixes the content bleed-through and allows links to be clicked again.
There is still an issue with the navigation links bleeding through. The fixed used on the body does not work on the links. It will take some more investigation.
=> documentation content clickability

bin/fin
Not all projects use the `docroot` folder. In fact Pantheon uses `web` and other projects have used the `public_html` folder. I'm suggesting we add in a method to autodetect what the `DOCROOT` for a project is.
=> Added option to help autodetect docroot

docs/content/service/cli/settings.md, docs/content/service/db/settings.md, docs/content/service/web/settings.md, docs/content/stack/checking-configuration.md, docs/content/stack/extend-images.md, docs/content/use-cases/docker-image.md, stacks/services.yml
Closes #908
The drupal7 and drupal7-advanced projects have pull requests to set the cli image to 7.1.
=> changes default cli image to php 7.2

docs/content/service/cli/settings.md
There was just one place in the docs where specific php versions were mentioned.
=> marks php 5.6 and 7.0 as deprecated, adds 7.3

docs/content/tools/wp-cli.md
No documentation for `wp-cli`
Added markdown file for wp-cli documentation & brief explanation; following [docs/tools/drush.md](https://github.com/docksal/docksal/blob/develop/docs/content/tools/drush.md) as a template
=> Start WP-CLI Documentation (Closes #926)

docs/Makefile, docs/README.md, docs/content/core/volumes.md
Included information for people who are using boot2docker (VirtualBox).
Was having issues learning how to build the docs locally when I found the Make file references docker directly. I am working with Boot2Docker. Made all of the commands set to defaults if not defined. Additionally, added info on committing updates to the docs.
=> Updated README and Makefile

bin/fin
Fixes a typo in the commands list:
>   kill                     	_Forcibely_ stop the machine
=> Fix "forcibely" typo in commands

bin/fin, docs/content/getting-started/docker-modes.md
There was a regression introduced in these docs in #658. 
`fin system reset network` step was dropped from the instructions for switching back to VirtualBox.
Reworked docs to suggest using `fin system start/stop` to unify steps.
Review docs here:
https://feature-docker-modes-doc-updates--docs-docksal-io.netlify.com/getting-started/docker-modes/
=> Docker mode docs updates

bin/fin
When Docker for Mac starts it automatically restarts these services. However this means that not the whole system might be started, e.g. resolver or something else might be not setup and there is no way for fin to know it. Preventing auto-restart of the services upon Docker restart will make fin to use system start.
fyi @sergey-zabolotny
=> Do not restart Docksal services on Docker restart, let fin do it instead

stacks/services.yml, stacks/stack-acquia.yml, stacks/stack-default.yml, stacks/stack-pantheon.yml
- Apache
- Switched `apache` service to `docksal/apache:2.4-2.3`
- Switched `web` service (legacy) to `docksal/web:2.2-apache2.4`
- MySQL
- Switched `mysql` service to  `docksal/mysql:5.6-1.4`
- Added new `mariadb` service: `docksal/mariadb:10.3-1.0`
- Redis
- Switched `redis` service to `wodby/redis:5.0`
- Nginx
- Added `nginx` service: `docksal/nginx:1.14-1.0`
- Varnish
- Switched `varnish` service to `docksal/varnish:6.1-2.0`
- Pinned `varnish` and `solr` versions in Acquia stack
- And... 🥁🥁🥁 Pantheon stack! 🎉
=> Stack updates

docs/content/tools/xdebug.md, stacks/services.yml
* Modified documentation for mapping the Drush Binary for VSCode
* Includes XDrush Debug variable mapped to `XDEBUG_ENABLED` as outlined in the latest Drush Launcher Release https://github.com/drush-ops/drush-launcher/releases/tag/0.6.0
* Includes Modifications to the services to include `PHP_IDE_CONFIG` variables
* Removed old note about running binary as the environment variable can be set
=> XDebug Changes

bin/fin
When running commands in custom commands with aliases there is an issue where the VIRTUAL_HOST and the PROJECT_SAFE_NAME
To reproduce:
* create two projects (project1 and project2)
* start both projects
* in project2 create a custom command in project2
```bash
#!/usr/bin/env bash
fin @project1 project status
```
* in project2 run `fin test`
* Should get a similar response
```
ERROR:  Another project is already using the name 'project2'
Change the name of the current project by renaming the project folder (folder name defines the project name and has to be unique)
or remove the other project's stack by running fin project remove in /Users/sean.dietrich/Desktop/docksal_test/project2
```
Solves https://github.com/docksal/docksal/issues/974
=> Added ability to run an alias in a custom command

docs/content/service/db/access.md, docs/content/tools/elasticsearch.md, examples/.docksal/docksal.env, stacks/services.yml
To make port forwarding comparable to MySQL and PostgreSQL, I added `"${ELASTICSEARCH_PORT_MAPPING:-9200}"` option in the `~/.docksal/stacks/services.yml` file. Running `fin develop` version and following this same pattern of setting the variable in my `docksal-local.env` file, I am not getting the results I expected. I'm still seeing port 32771.
```
testproject_elasticsearch_1_a9e0d576c113   /usr/local/bin/docker-entr ...   Up             0.0.0.0:32771->9200/tcp, 9300/tcp
```
I did a search for the `MYSQL_PORT_MAPPING` variable that does exist and work, but I can't find it, so I thought these were the only steps I needed to take. Am I missing a step?
=> adds ELASTICSEARCH_PORT_MAPPING env variable option

bin/fin
Full WSL support with both, Docker Desktop for Windows and VirtualBox modes.
Closes #851. Closes #865. Closes #973 (verify), Closes #936, Closes #749
- Dropped unused vm use cases
- `vm create`
- `vm active`
- `vm ip <IP>`
- Deprecated `fin vm start/stop` in favor of `fin system start/stop`
Closes #949 (verify), 
---
Testing / regressions testing:
=> WSL full support

docs/content/service/cli/settings.md, docs/content/stack/checking-configuration.md, docs/content/stack/extend-images.md, docs/content/troubleshooting/_index.md, docs/content/use-cases/docker-image.md
Updated documentation to point to the incremented version of the cli version but to also change the extending stock images to `docksal/cli:2-phpX.X`
Solves https://github.com/docksal/service-cli/issues/60
=> Updated documentation to for versions of CLI images

bin/fin
Closes #984
- The check adds roughly 40ms to the fin start time
Before
```
10:37:08 ~/Projects/drupal8
§ time fin debug is_docksal_running
real	0m0.443s
user	0m0.150s
sys	0m0.201s
10:37:39 ~/Projects/drupal8
§ time fin debug is_docksal_running
real	0m0.315s
user	0m0.150s
sys	0m0.139s
10:37:40 ~/Projects/drupal8
§ time fin debug is_docksal_running
real	0m0.301s
user	0m0.148s
sys	0m0.125s
10:37:41 ~/Projects/drupal8
§ time fin debug is_docksal_running
real	0m0.297s
user	0m0.150s
sys	0m0.126s
```
After
```
10:38:40 ~/Projects/drupal8
§ time fin debug is_docksal_running
real	0m0.483s
user	0m0.158s
sys	0m0.225s
10:38:42 ~/Projects/drupal8
§ time fin debug is_docksal_running
real	0m0.337s
user	0m0.159s
sys	0m0.143s
10:38:43 ~/Projects/drupal8
§ time fin debug is_docksal_running
real	0m0.366s …
```
=> Add check for Docksal IP binding to lo network interface

bin/fin, docs/content/fin/fin-help.md, scripts/fin-help-generate.sh
`exec` and `bash` will use sh by default and only use bash for `cli` and `db` (complex db functions input requires `bash` as well).
Closes #942 
Relates to #924
=> `exec` refactoring

bin/fin, docs/content/fin/custom-commands.md
As a project manager / lead developer, I would like to give my dev team a group of commands related to behat, but still allow them to type `fin behat` as a basic command. In order to do this, I need to be able to create a default command that will be executed when the name of the folder is typed. For example, I might have the following commands:
| Command | Runs something like ... |
| --- | --- |
| `fin behat` | `vendor/bin/behat "$@"` |
| `fin behat/info` | `vendor/bin/behat -d i --no-colors > available-tests.txt` |
To do this, I would make a folder structure as follows:
```
.docksal
commands
behat
.default
info
```
=> Feature: Enable creation of default commands for command groups

bin/fin
With fin 1.85.0 when doing a `fin update` it doesn't download the newly added Pantheon stack. So, I added the  `stack-pantheon.yml` to the `files_to_download` list in `update_config_files ()` function
=> Add Pantheon stack file to files_to_download list

bin/fin
This addresses the issue noted here https://github.com/docksal/docksal/issues/846#issuecomment-484269763. It does not completely resolve that, but at least allows help text to be printed.
=> Allow help text for commands located in symlinked directories.

bin/fin
Added docker run flag that will cause docker to remove the docksal/empty container after it exits.
=> Instruct docker to clean up exited docksal/empty container

bin/fin
Split cleanup into:
- cleanup - regular, Docksal stuff only
- cleanup_hard - regular + ALL stopped containers and dangling volumes/images
- cleanup_images - image cleanup wizard
The regular cleanup now drops orphaned stack volumes when orphaned containers are dropped and does not touch dangling volumes not created/managed under Docksal.
Fixes #1056
=> Cleanup refactoring

bin/fin, docs/content/stack/configuration-variables.md
This change adds a new environment variable `DOCKSAL_CHECK_FOR_UPDATES` which allows disabling automatically checking for updates. The default value is `true` but can be overridden by setting an environment variable or setting a value in `docksal.env`.
Rationale: we automatically deploy Docksal for development purposes and test new versions before releasing them across the board. If Docksal always automatically checks for new updates, users will be encouraged to run `fin update` instead of running on the fixed version we deploy. Using this new configuration value, we can disable the automatic update checks preventing the "fin update" message.
=> Allow disabling checking for updates

bin/fin, docs/content/stack/configuration-variables.md, stacks/services.yml
Fixes #1079
SSH key forwarding chain:
```
ci-agent (has keys loaded in ssh-gent) 
=> server (SSH_AUTH_SOCK) 
=> project cli container (mounted SSH_AUTH_SOCK from the host and overridden SSH_AUTH_SOCK variable)
```
This PR implements the last link of the chain.
SSH key(s) loaded in the ssh-agent on the client will be available on the server and in the target project's `cli` container only during the build time. Once the SSH connection from client drops, the ssh-agent socket becomes unavailable.
=> Adds SSH key forwarding support for cli

bin/fin, docs/content/stack/configuration-variables.md
Currently the user used to execute command on the `cli` container is hard coded to `docker`. This works well for the "official" docksal `cli` container provided in the stacks but may not be true for custom `cli` container.
This changes exports the `cli` user to a `CLI_USER` variable that can be set via the various docksal environments overrides.
=> Export CLI user to a configurable variable

bin/fin
Currently right now if a project uses Drush 9 there are some conflicts in the project and the acquia commands don't work. Until these are ported to 9 forcing drush8 to be used so that we can use the acquia commands.
=> Changed Drush to use Drush8 just for acquia pull commands

bin/fin
Fixed logic for how DBs were used and pulled. Previously wasn't reading the cached db in the `/tmp` directory but should now fix that issue
=> Fixed issue where date on cached db isn't checked properly

bin/fin
This commit limited the custom command finding depth to `2` to prevent infinite looping:
https://github.com/docksal/docksal/commit/9ea4932c8debe6df85a7a75635670f2d75820f51
A side effect of this was that our global custom commands were no longer listed, since we use a standardized format for our commands:
`{company}/{component}/{command}`
Since there is a lot of wiggle room between `2` and infinite, I suggest increasing the `maxdepth` to `4`. Note that commands still work regardless, it's just that they are not listed when running `fin`.
=> Increase custom command finding depth from 2 to 4

bin/fin, docs/content/stack/configuration-variables.md
This implements an SSH proxy in Docksal to support SSH agent forwarding for Mac / Windows. This means that key management through Docksal is now optional and you can use your local SSH agent such as the built-in `ssh-agent`, KeePass or really anything that sets `SSH_AUTH_SOCK`.
To make this work, the following MR in `service-ssh-agent` is needed:
https://github.com/docksal/service-ssh-agent/pull/8
**Usage**
- Set `DOCKSAL_SSH_AGENT_USE_HOST` to `1` (no longer limited to Linux)
- Run `fin system reset ssh-agent` to make sure the local proxy is started
- Run `fin up` within a project to make use of the SSH proxy
**Implementation details**
- Uses `socat` to start a local proxy. Unfortunately, this tool is not available by default on Mac or Windows. However, it is easily installed by `brew …
=> Implement an SSH auth proxy over TCP for Mac / Windows

docs/content/troubleshooting/common-issues.md
close #1139
By linking to "boilerplate" github projects, all of these will be shown without having to maintain a list in the docs (which may have existed previously, but doesn't now).
=> changes link of sample projects to the Docksal boilerplate list

docs/content/getting-started/project-setup.md
Since a space in the project path will cause issues for recognizing unique project names,
a warning notice is added to the project setup documentation page. Closes #1134
=> Adds notice about spaces in project paths

docs/content/tools/phpcs.md
fixes #1160 
I verified that the argument should be `--standard`.
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options
=> fixes phpcs standard command argument

docs/config.toml, docs/layouts/shortcodes/versions.html
fixes #1147 
Adds Docksal release versions to Hugo config. Fixes path for edit link.
=> updates hugo config for docs site

bin/fin, docs/content/stack/configuration-variables.md
In certain cases project containers would not start within 60 seconds. Despite usually you better investigate what exactly takes so long, sometimes it takes time for good reasons, that cannot or should not be worked around. 
This allows increasing the timeout.
Closes #1157
=> Make health check timeout configurable

bin/fin
As the check is currently, it only works in systems where the call to `/usr/bin/tty` returns an english text. This is not the case for some linux distributions like Ubuntu Bionic in brazilian portuguese which returns `não é um tty` instead of the expected `not a tty` message.
Getting the status from the call by using the `-s` flag should make the function more portable.
*Edit:* (And fix a bunch of "not a tty" errors on some developer machines i've tested custom docksal commands with background processes)
*Yet another edit:* This change was tested at Ubuntu Xenial and Bionic both in english and portuguese. I was hoping to see a result from Travis CI but... ¯\\_(ツ)\_/¯
=> Make the is_tty function language independent

bin/fin
This reverts the change in https://github.com/docksal/docksal/pull/1088/commits/3e6f1649b6c44eea9fe03a40a909f9d0dd18e2ed
ssh_key add is an expensive operation (~1.5s), so we should only call it where absolutely necessary.
=> Only call ssh_key add in up/restart/reset

bin/fin, tests/config.bats
- Setting `DOCKSAL_VOLUMES=nfs` on Mac (applies to Docker Desktop and VBox)
- Disabled the default NFS mount triggered at VM start for VBox
- Added switching between nfs volume and bind mount in `run_cli`
Closes #1025
=> Use NFS volumes on Mac by default

bin/fin
- Use unique home volumes for run-cli images
- Ensure run-cli volumes are cleaned up
- Added `io.docksal` label to run-cli volume. `fin cleanup` already drops volumes with the `io.docksal` label set.
Fixes #1225
=> Use unique home volumes for run-cli images

bin/fin
- Set `DOCKSAL_VOLUMES=bind` for existing Mac users (VirtualBox and Docker Desktop)
- This ensures we do not break existing project stacks by switching to nfs volumes as the default
- Show release notes URL after update
- Open release notes URL on Mac after update
TODOs:
=> NFS update safeguard for Mac users

bin/fin
Fixes the issue with the `is_tty()` on Alpine (one of the issues in https://github.com/docksal/docksal/issues/1233):
```
$ tty -s
tty: ignoring all arguments
/dev/pts/1
```
From `man tty` on macOS:
```
-s      Do not write the terminal name; only the exit status is affected when this option is specified.  The -s option is deprecated
in favor of the ``test -t 0'' command.
```
Tested on Mac Catalina 10.15.1, Ubuntu 18.04.1 LTS, WSL 17134 and PWD Alpine 3.10.3:
```
$ [[ -t 0 ]] && echo tty || echo 'not a tty'
tty
$ echo '[[ -t 0 ]] && echo tty || echo 'not a tty'' | bash
not a tty
```
=> Updated is_tty check

bin/fin
When running `fin bash`, a special value was passed to `_exec()` which sets the
command to run to an interactive shell. This caused the shell and login scripts
to be started twice, which causes an unnecessary delay before the shell is
available for the user.
This commit changes `_exec()` in the following ways:
* Instead of executing `cd {path}` to switch the working directory, use the
`--workdir` option of `docker exec` instead.
* Consider `__SHELL_INTERACTIVE__` a special case where we only run an
interactive shell without passing a command to run. This cuts time in half
for a `fin bash` invocation.
* Working directory is now also changed for the `web` container (when running
`fin bash web`).
=> Improve performance and functionality of `fin bash`

bin/fin
Running docker-compose incurs a pretty big start-up penalty which is especially
visible when running many `fin exec` statements sequentially, which might
happen when you e.g. write local development environment setup scripts for your
project.
Performance comparison:
docker-compose: 3.24s
docker:         1.41s
Command: `for i in {1..10}; do time fin exec echo test; done`
Averaged over 10 runs after removing the smallest and largest results.
Run on MacOS Catalina 10.15.2, Docker Desktop 2.1.0.5, Docker 19.03.5, Docker
Compose 1.24.1.
An obvious downside to this is that we're bypassing `docker-compose` and directly talking to `docker` to get the right container. However, we also do this for executing the command (running`docker exec` instead of `docker-compose exec`) so I figured this might …
=> Use docker instead of docker-compose for get_project_container_id()

bin/fin
When running Docksal with `DOCKSAL_SSH_AGENT_USE_HOST=1`, a side effect is that
the `SSH_AUTH_SOCK` env var is unset to prevent the default stack configuration
from picking this var up to mount a Unix socket inside the SSH agent container.
However, this happened too early and could break custom commands. For example:
1. Run `fin custom1` with `DOCKSAL_SSH_AGENT_USE_HOST=1`
2. Env var `SSH_AUTH_SOCK` is unset
3. Custom command `custom1` executes `fin up` which in turn wants to start
Docksal's system services
4. Starting the SSH agent fails since `SSH_AUTH_SOCK` is unset (see 2)
To fix most occurrences of this issue, move unsetting the `SSH_AUTH_SOCK` var
to just before the `docker-compose` invocation.
=> Fix SSH_AUTH_SOCK being unset for custom commands

bin/fin
Add http proxy variables to run_cli
fixes #1251
=> Add proxy variables to run cli

bin/fin
When running `fin db cli`, the default MySQL database is not selected. This only happens when extra arguments are provided.
This PR changes this behavior by always starting `mysql` with the database argument set to whatever `$db` or `$MYSQL_DATABASE` contains.
Note that this is MySQL/MariaDB-specific, but currently `fin db` only deals with those types of databases.
=> Provide database argument when running `fin db cli`

docs/content/fin/fin-pull.md
I added a link to the fin pull page to make it easier to find the documentation about where Drush site aliases can be configured in Docksal. This is helpful for those that are not familiar with Drush site aliases.
=> Added a link the documentation for Drush site Alias configuration in Docksal

docs/content/tools/ngrok.md, docs/content/troubleshooting/common-issues.md
Adds additional clarity around what to do when a cert has expired. Provides ngrok config file example with multiple tunnels.
=> Updates VM cert error docs, ngrok config example.

bin/fin
Sometimes `docksal-ssh-proxy` container remains connected to the project network. in this case command `fin rm -f` returns error:
```
Error response from daemon: error while removing network: network drupal8_default id 4abb0c2a4df4ca9475cf5bef8cdb790542bb663f1c87608c66b21fefd0225011 has active endpoints
```
and project network cant be deleted. this PR fix this issue
=> Fix issue "error while removing network: network id has active endpoints"

docs/content/getting-started/setup.md
This change adds comments so that when new versions of Docker Desktop are pointed at there is a reminder that those new versions also need to be referenced in the installation instructions on Docksal.io. See https://github.com/docksal/docksal.io/pull/19
=> Reminder to keep docksal.io installation instructions up to date

bin/fin
I discovered some issues with `fin exec` when executing scripts. There is a different flow when the first argument to `fin exec` is an existing file which has two issues:
1. The `$1` argument is duplicated to `$script_to_run` but no `shift` is executed, resulting in the `$1` argument being duplicated as part of `$@`
2. There are environment variables passed to `_exec` which result in garbled variables since the entire string is pulled through `printf`. I see no reason to define these variables again since they are also configured as environment variables in the Docker container itself. 
In the end, this makes things a bit simpler and fixes the usage of the `$PROJECT_ROOT` variable when executing scripts with `fin exec`.
=> Fix environment variables for `fin exec` running scripts

docs/content/tools/drupal.md
Changing instructions for Drupal to use environment variables injected into container as it is instructed on https://docs.docksal.io/getting-started/project-setup/#launching-your-first-docksal-stack
=> Use environment variables for DB connection

CHANGELOG.md, bin/fin, docs/content/fin/fin-help.md, docs/content/stack/configuration-variables.md
- fin v1.95.0
- Docker Desktop 2.3.0.2 compatibility fixes (Mac and Windows)
- Bind system services to `0.0.0.0` by default in virtualized environments (fixes #1268, fixes #1342)
- Dropped the dependency on DockerNAT interface on Windows (fixes #1276) 
- Do not configure DNS resolver with Docker Desktop for Windows
- Use the external `docksal.site` TLD with Docker Desktop for Windows v2.2.0.0+. This is necessary to have a working setup out of the box without the need to ask the user to manually configure DNS records using "fin hosts".
- Try the new external TDL for your Docksal projects!
```
fin config set --global DOCKSAL_DNS_DOMAIN=docksal.site
```
Note: This option is enforced with Docker Desktop for Windows 2.2.0.0+
=> Release 1.13.3

docs/config.toml
The versions config hasn't been updated since the last major version release. This includes our 1.13.x versions and the upcoming 1.14.0 release.
=> adds versions links for docs site

bin/fin
Previously, when running `fin db cli` the database parameter was not passed in
causing a MySQL CLI interface to open up without a database selected. This
fixes it by streamlining the invocation of `mysql`.
Changes include:
- Centralize a local `ptyCommand` variable to get rid of a separate `mysql` invocation
- Use optional expansion for the `-e` argument to get rid of another `mysql` invocation
- Use shell argument escaping for username, password and database name
=> Fix database selection when running `db cli` without arguments

docs/content/service/db/options.md, docs/content/service/other/elasticsearch.md, docs/content/service/web/options.md
I noticed some copy/paste errors that I didn't update with services. This updates the information for the correct service.
This also includes the documentation on elasticsearch persistent settings.
Closes #725
=> Documentation updates for services

bin/fin
If users want to stick with .docksal on Docker Desktop on Windows, then can do so by setting manually pinning DOCKSAL_DNS_DOMAIN: "fin config set --global DOCKSAL_DNS_DOMAIN=docksal", and then use "fin hosts add project.docksal" to manage DNS records using the OS hosts file.
Relates to #1352
=> Allow overriding DOCKSAL_DNS_DOMAIN with Docker Desktop 2.2.0.0+

bin/fin, docs/content/stack/configuration-variables.md, stacks/services.yml
Added ability for all services included in stacks to have logging options configured. Additionally, added logging options of the system services.
I used defaults of 10 files and 1m file size as the default.
=> Logging for Service Containers

docs/content/service/cli/cron.md
Documented how to set up a crontab and how to load the bash profile so that the commands and shell are available to run.
Closes https://github.com/docksal/service-cli/issues/187
=> Document how to run cron by loading bash shell

docs/content/stack/images-versions.md
Based on the PR for service-cli 2.11
The only question I had is will the default continue to be 7.3 or will it now be 7.4? I did not changed what was marked as default in docs.
=> updates software versions listed for cli:2.11

bin/fin, docs/content/stack/configuration-variables.md
In [v1.13.3](https://github.com/docksal/docksal/releases/tag/1.13.3) we switched to binding system services to `0.0.0.0` to workaround regressions in the recent Docker Desktop versions. Unfortunately, this brought up the old forgotten issues of conflicting ports on the host systems (#1348, #1375).
This PR adds  the `DOCKSAL_DNS_DISABLED` switch which can be used to turn off the docksal-dns built-in service and switch the Docksal instance to using the public `.docksal.site` base domain instead of the internal `.docksal`.
Usage:
```
fin config set --global DOCKSAL_DNS_DISABLED=1
fin system reset
```
Projects that do not set `VIRTUAL_HOST` variable manually will switch to the new `docksal.site` domain (after a `fin project restart`).
Projects that hardcode `VIRTUAL_HOST` will either need to …
=> Allow disabling build-in docksal-dns service

bin/fin
Fixes Debian based systems detection which specify multiple OS IDs in ID_LIKE (e.g., Pop!_OS has ID_LIKE="debian ubuntu")
Fixes #1374
=> Better handling of ID_LIKE in is_debian

bin/fin
- Reverted back to using IP binding for system services with VirtualBox/boot2docker
- Only use 0.0.0.0 for vhost-proxy and dns with Docker Desktop 2.2.0.0+ on Mac/Windows
- Added dns settings for run-cli
- Added "DOCKSAL: NETWORKING" sections in sysinfo
- Replaced "DOCKSAL: DNS"
- Prints network config variables
- Added check for DNS resolution/connectivity from containers (and not only host)
Fixes #1382
=> Docker networking adjustments

bin/fin
- Use `REQUIREMENTS_DOCKER` for Docker client version on all platforms
- Use `REQUIREMENTS_DOCKER` for Docker server version on Linux
- Use `REQUIREMENTS_DOCKER_DD` for Docker Desktop (Mac/Win)
- Use `REQUIREMENTS_DOCKER_B2D` for boot2docker
Fixes #1381, Fixes #1383
Testing:
=> Split docker client/server versions

CHANGELOG.md, bin/fin, docs/content/fin/fin-help.md, docs/content/getting-started/setup.md, docs/content/stack/configuration-variables.md
- fin v1.99.0
- Updated projects to include Drupal 9 boilerplate projects (#1385)
- Reverted back to using IP binding for system services with VirtualBox/boot2docker
- Only use `0.0.0.0` for vhost-proxy and dns with Docker Desktop 2.2.0.0+ on Mac/Windows
- Adjusted DNS settings for containers
- When `docksal-dns` is disabled, use DOCKSAL_DNS_UPSTREAM / DOCKSAL_DEFAULT_DNS as primary DNS
- Bump `REQUIREMENTS_DOCKER_DESKTOP` to 2.1.0.5
- This is the last version before networking regressions were introduced (#1268)
- Split docker versions based on environment (Linux, Docker Desktop, Boo2docker)
- `REQUIREMENTS_DOCKER='19.03.9'` - this is the earliest version available for Ubuntu 20.04 (focal) LTS
- `REQUIREMENTS_DOCKER_DD='19.03.8'` - this is the latest version available with Docker Desktop …
=> Release 1.14.1

stacks/services.yml
I needed to use Elasticsearch 7 for one of my projects and could not get it to start by default 
Found that I needed to use the following in my override Yaml file:
```yaml
elasticsearch:
extends:
file: ${HOME}/.docksal/stacks/services.yml
service: elasticsearch
image: elasticsearch:7.1.1
environment:
- bootstrap.memory_lock=true
- discovery.type=single-node
- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
```
Whereas it should be easier to use 
```bash
ELASTICSEARCH_IMAGE=elasticsearch:7.1.1
```
in my env file
Single node addon was also needed in order to allow the node to start
=> Update for Elasticsearch 7 compatibility

bin/fin
Fixes: https://github.com/docksal/docksal/issues/1395
=> Fix SSH_AUTH_SOCK_DIR owner in cases when the volume directory has been already created by docker (root user)

docs/content/getting-started/setup.md, docs/content/troubleshooting/common-issues.md
Added docs for missing SSE4.2 CPU instruction set.
Preview: https://deploy-preview-1414--docs-docksal-io.netlify.app/troubleshooting/common-issues#sse4_2
=> Added docs for missing SSE4.2 CPU instruction set

bin/fin, stacks/overrides-dd-bind.yml
- Fix bind mounts on Docker Desktop v2.3.0.2+ (fixes #1368)
- Increased precision in `ver_to_int` to 4 positions
- Fix `docker_desktop_version` check on Windows
Tested on:
=> Fix bind mounts on Docker Desktop for Mac/Windows v2.3.0.2+

docs/content/stack/extend-images.md
Let example use bash as default shell as long as docksal relies on it everywhere
If it's not a bash then it produces errors like this on container creation phase:
=> Fix Dockerfile example to use proper shell

bin/fin, docs/content/fin/fin-help.md
Resolves #1435 
- Added support for branch name in fin project create
- Regenerated fin help docs
Example:
```
$ fin project create --name=myd8 --repo=git@github.com:docksal/boilerplate-drupal8.git --branch=feature/circleci
Project folder:   /Users/leonid/Work/Labs/docksal/docksal/myd8
Project software: Custom git repository
Source repo:      git@github.com:docksal/boilerplate-drupal8.git
Source branch:    feature/circleci
Project URL:      http://myd8.docksal
Do you wish to proceed? [y/n]:
```
=> Support for branch name in "fin project create"

bin/fin
nfsd won't start or even do "checkexports" without the config file. Fixes #1431
=> Touch /etc/exports if missing

bin/fin
- rearranged items to be more logical
- print NFS settings for macOS regardless of the mode (VBOx or Docker Desktop)
- print DOCKER_HOST unconditionally (may be helpful in any case)
- list all projects, not just active
=> fin sysinfo improvements

docs/content/getting-started/project-setup.md
Fix the broken "Read more" link to `ssh-agent`
On the [Launch a Project Stack] document page, the link to "Read more" about `ssh-agent` goes to: https://docs.docksal.io/getting-started/project-setup/(/core/system-ssh-agent/) - a 404 page. The correct link appears to be: https://docs.docksal.io/core/system-ssh-agent/
[Launch a Project Stack]: https://docs.docksal.io/getting-started/project-setup/
=> (minor) fix link in "Launch a Project Stack" documentation

bin/fin, docs/content/stack/configuration-variables.md, stacks/services.yml
- Added `DOCKSAL_CONTAINER_HEALTHCHECK_INTERVAL` variable
- Default: `10s` (was `5s`, set in individual container image Docketfile's)
- Can be used to increase container healthcheck interval and thus help reduce idle load produced by healthchecks
Resolves #1453
=> Make healthcheck interval configurable

docs/content/getting-started/setup.md, docs/static/robots-disallow.txt, netlify.toml
- Block search engines on feature/version branches of the docs
- https://feature-docs-rtd-fixes--docs-docksal-io.netlify.app/robots.txt
- Docs: added a redirect for a common old URL used on RTD …
- https://feature-docs-rtd-fixes--docs-docksal-io.netlify.app/en/master/getting-started/env-setup/ => https://feature-docs-rtd-fixes--docs-docksal-io.netlify.app/getting-started/setup/
Fixes #1447
=> Docs fixes

bin/fin
There were more spaces for 3 of the project types than the rest which made them look off. This PR just removes those spaces for those 3 projects to line them all up.
=> fixes spaces in project create for consistency

.github/workflows/default.yaml, tests/project.bats, tests/scripts/acquia.sh, tests/scripts/boilerplates.sh, tests/scripts/commands.sh, tests/scripts/config.sh, tests/scripts/db.sh, tests/scripts/drush.sh, tests/scripts/github-build-trigger, tests/scripts/macos.sh, tests/scripts/pantheon.sh, tests/scripts/platform.sh, tests/scripts/project.sh, tests/scripts/quicktest.sh, tests/scripts/system.sh, tests/scripts/wp.sh
- GitHun Actions config cleanup/overhaul
- Fixed Docksal domain in project.bats tests
- Disabled TTY vs no-TTY tests …
- It is irrelevant in Github Actions, since Github Actions does not emulate a TTY (like Travis CI does).
- Use `set -euo pipefail` in test scripts …
- Otherwise only the last failure in the script counts as test failure...
- Fixed typo in tests/scripts/commands.sh
=> Fixed and cleaned up build and tests

bin/fin, docs/content/fin/custom-commands.md
Added option so that `fin` could be sourced for addons and commands and take advantage of the functions already provided in the main file.
Example of the usage:
```bash
fin=`which fin`
[[ -f ${fin} ]] && source $fin
```
=> Added option for addons and other files to source the fin file

docs/content/service/db/options.md, docs/content/service/web/options.md, docs/content/stack/understanding-stack-config.md
With the merging of the platformsh alike stack, documentation needed to be added to the stack options.
=> adds documentation for platformsh alike stack

bin/fin, docs/content/stack/images-versions.md, stacks/services.yml
The updated run-cli is necessary to have access now to Composer 2, which more projects are now updated to require.
The basic service cli update was missed with the last update.
=> Updating cli version to latest

stacks/overrides-dd-bind.yml, stacks/overrides-ide.yml, stacks/overrides-xhprof.yml, stacks/services.yml, stacks/stack-acquia.yml, stacks/stack-default-nodb.yml, stacks/stack-default.yml, stacks/stack-node.yml, stacks/stack-pantheon.yml, stacks/stack-platformsh.yml, stacks/volumes-bind.yml, stacks/volumes-nfs.yml, stacks/volumes-none.yml, stacks/volumes-unison.yml
v2 and v3 Docker Compose file formats were [merged together](https://github.com/docker/compose/pull/7588) in docker-compose v1.27+
This means, we can safely switch to the latest compose file v3.9 and continue to use `extends` + all of the new features and options that we were not able to use while stuck on 2.1, like [extension-fields](https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields) and [yaml anchors](https://yaml.org/spec/1.2/spec.html#id2765878).
Moreover, the "version" property is now optional and combining files with different versions will not result in an error. This used to be a major blocker for us to even consider updating the compose file format version, since that would be a breaking change for every single Docksal project out there.
Closes: #701
=> Switch to Docker Compose file v3

docs/content/stack/configuration-variables.md
Added DOCKSAL_VERSION and DOCKSAL_USE_RC variable descriptions and usage.
Found and fixed a variable that was using ## instead of ### like the rest.
Closes #254
=> adds information on variables used to pin versions and use RC

docs/content/tools/xdebug.md
Modified XDebug documentation and reverted port back to 9000 as the port used for v3.x will use 9003 now.
To not introduce breaking change we will set the default port to be 9000.
Reference: https://github.com/docksal/service-cli/pull/218
=> Updated documentation for Xdebug

bin/fin
- Replaced which with command in shell function wrappers: `pwd`, `docker`, `docker-compose` (see https://github.com/docksal/docksal/issues/1496#issuecomment-867231686)
- Dropped `docker-machine` wrapper (microsoft/WSL#4078 is now resolved)
Resolves #1496
=> Replaced which with command in shell function wrappers

docs/content/core/system-vhost-proxy.md
closes #1440
https://deploy-preview-1526--docs-docksal-io.netlify.app/core/system-vhost-proxy/#using-arbitrary-ports
=> adds documentation on using arbitrary ports

docs/content/tools/xdebug.md, stacks/overrides-ide.yml
- Updated IDE settings for xdebug v3 compatibility
- Updated xdebug docs. Clarified that xdebug v3 was introduced in docksal/cli v2.13
Related: https://github.com/docksal/service-cli/pull/248
=> IDE config fix for xdebug v3

docs/content/tools/xdebug.md, stacks/overrides-ide.yml, stacks/services.yml
This will prevent breaking changes for custom stacks or stacks that pin the `CLI_IMAGE` version to older versions of docksal/cli (v2.12 and below), which ship with XDebug v2.
Also, updated XDebug docs to explain what we do to support both versions concurrently.
This is a followup to https://github.com/docksal/docksal/pull/1485#pullrequestreview-635819061
=> Preserving compatibility with XDebug v2

bin/fin, docs/content/stack/images-versions.md, stacks/services.yml
cli v3 is a major release. The most notable changes are:
- PHP 8.0 image version
- arm64 support
There are also some potentially breaking changes. Details here:
https://github.com/docksal/service-cli/releases/tag/v3.0.0
To test:
```
fin config set CLI_IMAGE=docksal/cli:php7.4-3.0
fin up
```
=> Switched cli to docksal/cli:php7.4-3.0

bin/fin
- Revised terminal colors
- Use a standard format for all color definitions
- Use black text color (30) when there is a background color set
- Renamed `echo-alert` to `echo-notice`
- Use `echo-notice` to display post-update messages
- Use `echo-warning` before destructive operations
- Typo fixes
Testing predefined colors:
```
COLORS=(green green_bg yellow yellow_bold yellow_bg red red_bg blue lime acqua magenta lightmagenta lightmagenta_bg)
for color in "${COLORS[@]}"; do fin debug 'echo -e '$color': ${'$color'}Hello world ${NC}'; done
```
Testing alerts:
```
fin debug 'echo-notice "Title" "Message text"'
fin debug 'echo-warning "Title" "Message text"'
fin debug 'echo-error "Title" "Message text"'
```
=> Terminal colors and alert updates

docs/content/troubleshooting/common-issues.md
Existing docs cover two very similar issues and propose solving them with almost identical steps. Some users may not follow the 2nd part thinking they've already done it.
In reality, both cases can be fixes with a single command: 
```bash
fin docker-machine regenerate-certs --client-certs --force docksal
```
Preview: https://deploy-preview-1544--docs-docksal-io.netlify.app/troubleshooting/common-issues/#issue-02
=> Simplified troubleshooting docs around Docker Machine TLS certs

docs/content/stack/configuration-variables.md
Documentation for the HOSTING_* variables was missing from the configuration variables page.
Starting here: https://deploy-preview-1539--docs-docksal-io.netlify.app/stack/configuration-variables/#hosting-env
=> adds hosting variables documentation

docs/content/stack/custom-configuration.md
Fix typo in reference to `docksal.yml` file.
This is visible at https://docs.docksal.io/stack/custom-configuration/#customized-configuration
=> Fix typo in reference to `docksal.yml` file in custom-configuration docs

CHANGELOG.md, bin/fin, docs/config.toml, docs/content/fin/fin-help.md
- fin v1.107.1
- Fixed terminal colors in `fin` broken on some systems after update to v1.16.1
=> Release 1.16.2

stacks/stack-pantheon.yml
Small update to use the default MariaDB version in the Pantheon stack.
Closes #1590
=> Updating pantheon stack to use default MariaDB version.

docs/content/fin/addons.md
Docs referencing global addons don't actually say how to install them globally. Let's make it explicit.
=> Add instructions for installing an addon globally

stacks/stack-platformsh.yml
Now that docksal offers mariadb:10.4, update platformsh stack to match [Platform.sh Drupal 9 template](https://github.com/platformsh-templates/drupal9).
Redis stays at 6.0 as that is recommended version in [docs.platform.sh](https://docs.platform.sh/guides/drupal9/redis.html).
=> Update stack-platformsh.yml mariadb version

bin/fin
The new platformsh stack is not actually installed/updated on local machine when installing or upgrading docksal.
Added entry to STACK variables and in `update_config_files` function to ensure the new stack is installed.
=> Add missing platformsh stack

bin/fin, docs/content/getting-started/setup.md, docs/content/troubleshooting/common-issues.md
- Bump VirtualBox to v6.1.32 
- Allow Docksal subnet IPs to be assigned to a VirtualBox host-only adapter (VirtualBox v6.1.28+)
- Simplified macOS + VirtualBox installation instructions in docs
- Recent version of VirtualBox seem to be properly handling the Kernel Extension (kext) installation check and approval.
Docs updates preview:
- https://deploy-preview-1622--docs-docksal-io.netlify.app/getting-started/setup/#install-macos-virtualbox
- https://deploy-preview-1622--docs-docksal-io.netlify.app/troubleshooting/common-issues/#issue-12
Fixes #1596
=> VirtualBox on macOS Monterey (12.x) support

stacks/services.yml
Blackfire Agent v1 is reaching end of life.
This PR ensures that v2 is used.
=> Use Blackfire Agent v2

.github/workflows/default.yaml, README.md
- Renamed workflow to Default 
- shields.io Github Action badges rely on workflow names in the URL and that does not work when the name has spaces
- Updated Release and Build badges in readme 
- Replaced Travis build status badge with Github Actions.
Preview updated badges: https://github.com/docksal/docksal/tree/feature/readme-badges
Fixes #1547, closes #1548
=> Readme badges updates

bin/fin, docs/content/service/cli/settings.md, docs/content/service/web/multiple-web.md, docs/content/service/web/settings.md, docs/content/stack/checking-configuration.md, docs/content/stack/extend-images.md, docs/content/stack/images-versions.md, examples/.docksal/docksal.env, stacks/services.yml, stacks/stack-pantheon.yml, stacks/stack-platformsh.yml
- Switched `apache` service to `docksal/apache:2.4-2.4`
- Switched `nginx` to `docksal/nginx:1.20-1.2`
- Switched `mysql` to `docksal/mysql:8.0-2.0`
- 8.0 is the only amd64/arm64 compatible version (image based on Oracle Linux)
- Switched `mariadb` to `docksal/mariadb:10.6-1.3`
- Note: Pantheon and Platform are pinned at docksal/mariadb:10.4-1.3
- Switch `cli` to `docksal/cli:php7.4-3.1` in all stacks and "fin run-cli" command
These new image versions are multi-arch with amd64/arm64 platform support.
=> Image updates in stacks

bin/fin
This helped with running `docksal/vhost-proxy` tests in Docker Desktop on Mac.
The volume would get stalled when vhost-proxy attempts to access it (remove dangling project folders) using the old implementation.
=> Replaced docksal_projects volume with a simple volume mount

stacks/stack-pantheon.yml
Service stack references DB_IMAGE in the CLI stack
=> Fixed CLI_IMAGE reference in stack

.github/workflows/default.yaml, bin/fin, stacks/overrides-cloudflared.yml, stacks/services.yml, tests/scripts/share-v2.sh, tests/share-v2.bats
Creates a temporary public URL for the project using a [free Cloudflare Tunnel](https://try.cloudflare.com/) ([formerly Argo Tunnel](https://developers.cloudflare.com/cloudflare-one/glossary#cloudflare-tunnel)).
This integration is implemented similar to the IDE integration.
`cloudflared` services runs as part of the project's Docker Compose stack.
It can be enabled via an environment variable:
```
❯ fin config set --env=local CLOUDFLARED_ENABLED=1
Added value for CLOUDFLARED_ENABLED into /Users/leonid/Work/Projects/test/.docksal/docksal-local.env
~/Work/Projects/test main*
❯ fin project start
Starting services...
test_db_1 is up-to-date
test_cli_1 is up-to-date
test_web_1 is up-to-date
Creating test_cloudflared_1 ... done
Project URL: http://test.docksal.site
```
It also can be managed …
=> fin share-v2 and cloudflared service

bin/fin
While we can certainly keep the boilerplate repos for reference, with Drupal 8 now past EOL, it should no longer be an option for a new project.
=> removes Drupal 8 options from project create

docs/content/fin/fin-help.md, docs/content/tools/cloudflare-tunnel.md, scripts/fin-help-generate.sh, stacks/overrides-cloudflared.yml, stacks/services.yml
The information is incomplete. Without being able to run it, I'm not sure what some of the expected processes are. This is simply built by starting with what we have from ngrok and the fin help text and examples in #1551
=> adds initial cloudflare tunnel doc page

bin/fin
This was introduced in fce8f506992cd8127a9f5ad519e5b130e987b10a and then dropped unintentionally in fcb051c6c3e86b53328d426d0c67816c6ab06e0c.
Fixes #1668
=> Make DOCKSAL_ENVIRONMENT variable visible in custom commands and addons by default

bin/fin
Fixes #1711 which is due to the move of Docker API to version 2. 
Be aware that with the new API version the list of resulting tags is limited to 100 at least for non-authenticated requests. A pagination is at disposal to retrieve all the results.
=> Fix fin image registry image_name command

stacks/overrides-gitpod.yml
This PR fixes an issue with Gitpod network setup.
```
#
#
#
```
Please see a similar issue in ddev project -
https://github.com/drud/ddev/issues/3766
This is how it was solved temporarily in DrupalPod -
https://github.com/shaal/DrupalPod/pull/84
=> Fix MTU settings on Gitpod to 1440

bin/fin
Fin share checks if a web container is running inside the project. The check looks for "Up" but "fin ps web" returns "running", therefore reporting the project as not having a running web container.
=> Fix checking web container in project

docs/content/service/other/apache-solr.md
The current services settings utilize the solr:8.6-edge image. This updates the documentation to reflect that as the current version and removes the Solr 4 instructions.
=> removes solr 4 instructions and updates the listed default version to 8

stacks/stack-platformsh.yml
Hi.
It seems to me that platform.sh stack is still connected to PHP.74 which is very old.
It is better to change it to the 8.1 which is compatible with the last Drupal9/10
=> Update minimal PHP for Platform.sh

stacks/overrides-xhprof.yml
Updates default xhprof stack to use woodby/xhprof:2-3.7.6 which is compatible with M1 and Intel macs.
=> Update xhprof to work with m1.

docs/content/tools/mkcert.md
When following directions, there is an error
> > fin addon install mkcert
> Downloading addon hook files...
>   mkcert.pre-install
> Running pre-install hook...
> [PRE-INSTALL] ERROR: Mkcert addon should installed globally, use 'fin addon install mkcert -g'
> Pre-install hook has failed and aborted the installation.
>
=> Update mkcert.md addon step to use global option

docs/content/core/volumes.md
This adds Mutagen.io documentation to the volumes.md file.  It describes two options for using Mutagen as offered by mutagen.io. 
Preview: https://deploy-preview-1741--docs-docksal-io.netlify.app/core/volumes/
=> Adding Mutagen docs

.github/workflows/default.yaml, CHANGELOG.md, bin/fin, docs/content/getting-started/setup.md, tests/project.bats
❗**IMPORTANT:** This release addresses a bug in the update process introduced in [v1.17.0](https://github.com/docksal/docksal/releases/tag/v1.17.0).
Please use the command below to force the update to this release.
```bash
DOCKSAL_VERSION=v1.18.1 fin update
```
- fin v1.113.0
- Fixed network issues after project stack stop/restart
- Fixed update process
- Switched CI builds to `actions/checkout@v3`
- Updated Docker Desktop links in setup.md docs
=> Release 1.18.1

.github/workflows/default.yaml, CHANGELOG.md, bin/fin
❗**IMPORTANT:** This release addresses a bug in the update process introduced in [v1.17.0](https://github.com/docksal/docksal/releases/tag/v1.17.0).
Please use the command below to force the update to this release.
```bash
DOCKSAL_VERSION=v1.18.2 fin update
```
- fin v1.113.1
- Fixed stack files download URL
- Replaced the legacy `set-output` command in GitHub Actions
=> Release 1.18.2

bin/fin
fixes #1774 
Adds the --build option to recently added docker-compose create command, ensuring dockerfiles are used when project start is run.
=> Add --build option to docker-compose create to use dockerfiles

docs/content/fin/fin.md
Was incorrect tense of word, corrected simple error needed to be project in singular form
=> Spelling / Grammer correction

docs/content/stack/images-versions.md, stacks/services.yml
We have new cli images. This updates to the latest with php 8.3 as the default.
=> Switch default cli image to docksal/cli:php8.3-3.7

docs/content/core/system-vhost-proxy.md, docs/content/service/other/mailpit.md, docs/content/stack/custom-configuration.md, stacks/services.yml
This was pointed out in the addons repo:
https://github.com/docksal/addons/issues/93
Here is the mailpit repo and the latest tag is 1.15.1, which was released Mar 30, 2024.
https://github.com/axllent/mailpit
=> replaces mailhog service with mailpit

bin/fin
Both will be completely removed in the following release
Fixes #1777. Closes #1779
=> Disable dns service and resolver configuration by default
