docksal/docksal

bin/fin
Also no IP switching, network interface fix (kill the interface when VM is removed).
=> Default IP 192.168.64.100

bin/fin
Fixes https://github.com/docksal/docksal/issues/3
The fix is applied during `fin install tools` on Windows and can also be initiated as a standalone command: `fin fix-smb`.
=> Fix/optimize Windows network settings for file sharing. Fixes #3

bin/fin
* Fixed the need for sudo
* Added a reminder to run `newgrp docker`
* Split `update images` into `update images | system-images | project-images`
=> Install tools improvements on Ubuntu

bin/fin
Delete echo - it shows command instead of run it.
=> Delete echo for download command

docs/behat.md
- Also removed trailing whitespace on lines
=> Various grammar corrections to behat.md

docs/mail.md
Change docker-compose.yml reference to docksal.yml
=> Update mail doc

bin/fin
Allows easy viewing Docksal's team images and their tags on Docker Hub
=> fin config images command

.travis.yml, bin/fin, docs/docksal-stack.md, docs/project-customize.md, tests/smoke-test-config.bats
Accept stack as parameter. Possible values: empty value, default (same as empty), acquia
Do not remove .docksal folder if exists. Just overwrite config files.
=> fin config generate changes

bin/fin, docs/env-setup.md, docs/index.md, docs/project-customize.md, tests/smoke-test-general.bats
Use default database. Make database parameter optional.
Use stdin/stdout for importing/dumping when no file provided
Improve environment setup documentation, make it easier to follow as an instruction for newcomers.
=> Merge bleeding edge

bin/fin
Checked on local with docker-engine 1.13.0 downgrade to 1.12.6 with fin update --tools command
=> Pin docker-engine version.

docs/behat.md
Related to https://github.com/docksal/docksal/issues/121
=> Docs: updated setup instructions for behat (custom command).

bin/fin, examples/.docksal/docksal.yml, stacks/services.yml, stacks/stack-acquia-static.yml, stacks/stack-default-static.yml, tests/smoke-test-general.bats, tests/smoke-test-system.bats
Addresses the issue with containers not being able to resolve .docksal domains.
=> DNS settings for all services

bin/fin
Minimal OS and version stats
Ping home is done on:
- daily
- `fin --version`
- `fin sysinfo`
=> Docksal usage stats

bin/fin
Includes additional refactoring.
=> 1.3.2. Fix initial installation process on Ubuntu

bin/fin
=> Allow colors in custom help.

bin/fin
- Adds `fin image` command for image management
- Removes the DigitalOcean docker machine use case
- Adds `fin update --portable` (WIP). Currently only supports boot2docker.iso and Docksal system images
=> fin image and fin update --portable

bin/fin
Adds custom commands from project and global to the bash auto completion
=> add custom commands to bash autocomplete

bin/fin, docs/fin/fin.md
- 1.25.0. fin db cli now accepts query as an argument and also accepts --db parameter to specify database to run query against.
- 1.26.0. fin db create and fin db drop commands added
=> New DB commands and improvements

bin/fin
=> Clarifying that the update notification doesn't itself run the update.

bin/fin
=> Fix the bug that virtualbox update breaks docker-machine upgrade.

bin/fin
Support for installing and using Docksal from Ubuntu application for Windows 10. Requires Docker for Windows. Virtualbox is not supported.
=> WSL support (beta)

docs/advanced/networking.md
=> Fix indentation of networking example

docs/getting-started/setup.md
=> Fix typo in setup.md

docs/tools/apache-solr.md
=> Fixed typo in apache-solr.md

bin/fin
This is to solve the following feature pull request: https://github.com/docksal/docksal/pull/461
=> Namespacing of Commands

docs/fin/custom-commands.md
Updated Custom Commands doc to include the recent #526 Pull Request.
=> Custom commands grouping docs

.travis.yml
Modified the travis.yml file to account for external PRs
=> Updated Travis Config to work with External PRs

docs/advanced/stack-config.md, stacks/services.yml
Started to Document all variables that are currently being used for extending Docksal.
I believe this solves #383 and solves #464
=> Added Documentation around variables

docs/tools/redis.md, mkdocs.yml
=> Added docs for using redis

bin/fin
Added REPO selection for Symfony both webapp and skeleton.
Solves #546
=> Added repos for symfony

bin/fin
Added support to create a project for [Backdrop CMS](https://github.com/docksal/example-backdrop)
=> Added Project Backdrop

bin/fin, docs/advanced/db-sandbox.md, docs/advanced/dns-resolver.md, docs/advanced/drupal-settings.md, docs/advanced/extend-images.md, docs/advanced/multiple-projects.md, docs/advanced/stack-config.md, docs/advanced/stack.md, docs/advanced/volumes.md, docs/fin/addons.md, docs/fin/custom-commands.md, docs/fin/fin.md, docs/getting-started/env-setup.md, docs/getting-started/project-setup.md, docs/index.md, docs/tools/behat.md, docs/tools/ngrok.md, docs/tools/phpcs.md, docs/tools/redis.md, docs/tools/xdebug.md, docs/troubleshooting.md
Usage of "e.g." is always followed by a comma and is preceded with a comma or placed in parentheses. It should not start a sentence as it introduces an apposition in a sentence.
Checked consistency of usage for no periods at the end of bullet points, semicolons with "run" before commands, and the oxford comma placement.
The oxford comma (the comma before the final item of a list) is recommended for readability as it removes any ambiguity. This is especially true where a list has both an "and" and an "or" in it.
=> Documentation updates

docs/getting-started/setup.md
Updated sample projects list in the docs
=> Updated options for projects.

bin/fin
=> Beautify and re-organize project wizard

docs/tools/xdebug.md
Added docs for configuring and using Atom and PHP XDebug with Docksal
Solves #487
=> Added Atom Xdebug docs

bin/fin, docs/fin/fin-help-generate.sh
fyi @lmakarov @sean-e-dietrich
=> Fin help doc generator

docs/fin/fin-run-cli.md
Just minor typos with the new doc page.
=> Fixed minor typos

README.md, docs/getting-started/project-setup.md, docs/index.md, docs/tools/xdebug.md, docs/troubleshooting-smb.md, docs/troubleshooting.md
=> Documentation update

bin/fin, docs/tools/ngrok.md
Added ability for ngrok options to be specified at the command line
```
fin share --host-header=test.example.docksal
```
Solves #601
=> Ngrok Options through command

bin/fin, tests/smoke-test-general.bats
This is a rewrite of the PR https://github.com/docksal/docksal/pull/618
This includes a test for #526
=> Fin Commands Test and Fix

bin/fin
Debugged issues on Linux Mint. Mint detection was not working properly. Swapping it for Linux detection as anyways this is the proper target.
=> Merge in changes from debug

docs/tools/ngrok.md, examples/.docksal/etc/ngrok/ngrok.yml
This consolidates some of Sean's suggested changes for these docs as well as changes wording to make it consistent with other documentation.
=> Documentation

bin/fin
=> Improve VirtualBox on Windows installation

docs/getting-started/system-requirements.md, docs/troubleshooting.md
=> Updated docs around windows and disabling hyper-v

docs/fin/fin-run-cli.md, docs/getting-started/system-requirements.md, docs/troubleshooting.md
Recent additions to documentation needed a little grammar love. I also included the documentation fixes for run-cli from fjmk.
=> Fixes typos, improves link clicks, adds fix for run-cli documentation

bin/fin
Added category for GO and moved Hugo under to fix category.
=> Updated project wizard and added category for GO, moved Hugo

bin/fin, docs/tools/composer.md, mkdocs.yml
Added command to make running composer commands easier. Also to make it known that Composer is a tool that is installed already within the container.
=> Composer command

bin/fin, tests/smoke-test-general.bats
* Added warning into place to let user know that the VIRTUAL_HOST has been modified.
* Converted virtual host to all lower case
* Converted underscores to dashes
* Added test to make sure this is happening
* Additionally removed all characters that aren't a `-` or `0-9` or `a-z` or `.`
Should Solve #430
=> Add a check in place, so that virtual hosts comply with browser standards

bin/fin
Closes #586
FYI @sean-e-dietrich
=> Auto-detect upstream DNS when possible

docs/fin/fin-run-cli.md
=> Fix fun > fin typo

bin/fin
Solves #174 
Added option for Drupal8 Composer project within `fin project create` method.
=> Added Drupal8 Composer Repo as list of options

bin/fin
Fixes an issue when fin config get/set/rm does not work with an alias
=> Fix fin @alias config get/set/rm

bin/fin
Fixed fin share command as the container name was not included int he `sh -c` command.
Additionally, I added the `-host-header` back in if there are no arguments supplied.
Closes #674
=> Adjusted fin share command

bin/fin, tests/smoke-test-general.bats
The following is to test the basic `fin share` command in light of issue #674
=> NGROK Automated Tests

tests/smoke-test-general.bats
* Uncommented skip in `fin share` test
* Adjusted namespacing command test
=> Fixed tests for smoke general

docs/advanced/cron.md
Updates for Sean's documentation of feature. This just request it be merged into that same feature branch since it has not been merged to develop.
=> Cron documentation updates

.travis.yml, tests/quicktest.bats
Use `-i` switch of the custom docksal/bats to interactively echo output from all the commands
=> Custom docksal/bats

.travis.yml, bin/fin, tests/general.bats, tests/quicktest.bats
- Create new built-in init
- It can be overridden
=> New built-in `init`

bin/fin
Updated URL used for checking for Pre Releases
=> Modified URL used for latest tag

docs/tools/xdebug.md
Removed features revert all command as this can be potentially harmful and disruptive to projects
Closes #734
=> Fixed the Xdebug doc

bin/fin, tests/system.bats
=> Skip loading SSH keys that already exist in the ssh-agent. Fixes #773

docs/tools/drupal-console.md
=> Fix typo in Drupal Console documentation.

docs/content/_index.md
Reading through the updated docs, I found a few typos. I also added some suggested word choice changes.
=> fixes typos, minor wording changes

bin/fin
Changed the stage where we check for the Docksal Version
Fixes #825
=> Change stage where DOCKSAL_VERSION is set

bin/fin
=> Only disconnect network when all containers are being removed

bin/fin
Refactored the stack downloads as the DOCKSAL_VERSION needs to be evaluated after it is set for the RC feature
=> Refactored Stack Downloads

docs/content/stack/config.md
I couldn't find another example where the warning title was included. Update as needed.
=> updates warning markup

docs/content/tools/redis.md, stacks/services.yml
Added Redis to services. But also am passing all available variables so they could be set within `docksal.env` with ease.
Fixes #874
=> Added redis to services and updated documentation

bin/fin
Made modification to ngrok command as when specifying the `ngrok start with a config file` it doesn't allow for a tunnel connection.
=> Adjusted arguments for NGROK

docs/content/service/cli/nodejs.md, docs/content/troubleshooting/_index.md, docs/content/troubleshooting/common-issues.md, docs/content/troubleshooting/windows-smb.md, docs/content/use-cases/_index.md, docs/content/use-cases/auto-start-stop.md, docs/content/use-cases/composer-command.md, docs/content/use-cases/multiple-solr-cores.md, docs/content/use-cases/multiple-web.md, docs/content/use-cases/nodejs.md, docs/content/use-cases/shared-cache-volumes.md
Adding a section to the documentation on advanced use cases that have come up in issues. Currently addressed are:
#684 
#685 
#348 
#231 
#798 
#464 
#744 
Please edit, adjust, add to this documentation.
=> Documenting advanced use cases

docs/content/core/vm.md, docs/content/fin/custom-commands.md, docs/content/stack/extend-images.md, docs/content/use-cases/docker-image.md
Big updates to extending images - requires review.
Reorders options in order of complexity and notes use cases for each, adds more info on use with custom commands, custom Docker image.
Custom command updates include minor typo fixes, link to blog post on writing custom commands, updates example variables, and adds notice of environment variables available to commands.
Closes #443 
Closes #896 
Closes #722
=> Documentation Additions

stacks/services.yml
Has no ticket.
Related ticket: #905
cc @sean-e-dietrich
=> Remove deprecated `db` declaration

docs/content/tools/elasticsearch.md, stacks/services.yml
Closes #725 
cc @sean-e-dietrich
=> Add Elastic Search service and docs (closes #725)

docs/layouts/partials/custom-header.html, docs/layouts/partials/menu-footer.html, docs/layouts/partials/search.html, docs/static/css/theme-docksal.css
Closes #809
Additional css was added to keep documentation from bleeding through to the results box and keeping the size and padding of the search box as it was.
=> adds Algolia search to documentation

stacks/services.yml, stacks/stack-acquia.yml, stacks/stack-default-nodb.yml, stacks/stack-default.yml
=> Adds `apache` service replacing `web` service in stacks. (closes #905)

docs/content/tools/apache-solr.md
Updates list of available images for documentation
=> updates solr options

docs/content/tools/xdebug.md
Added note that Drush Launcher will not work with XDebug.
Fixes #786 
Also removed extra config in the section for vscode as this is part of variables already baked in.
=> Added note about Drush9 and Xdebug

bin/fin
Implements healthcheck for all services (Closes #554)
=> Implements healthcheck for all services (Closes #554)

docs/content/getting-started/setup.md
=> adds information on use of sudo on installation

docs/content/core/volumes.md
=> adds notice for moving a project on host

docs/static/css/theme-docksal.css
CSS fixes for pages where the content does not go full length.
=> fixes css for better positioning

bin/fin
=> Improve error messaging in case of problems with /etc/exports file

docs/content/stack/extend-images.md
https://github.com/docksal/docksal/issues/798#issuecomment-429045813
=> Updating documentation regarding nvm in Dockerfile.

docs/content/fin/fin-pull.md
Fixed code base of old variable name within Pull Docs.
=> Fixed variable name

docs/content/service/web/settings.md
=> updates fin command for apache config overrides

docs/content/service/cli/settings.md, docs/content/stack/extend-images.md, docs/content/stack/images-versions.md
Covers some vital images for now. 
https://deploy-preview-1070--docs-docksal-io.netlify.com/stack/images-versions
Needs to be appended and maintained in future
Closes #1038
=> Create a doc on available image versions

bin/fin, docs/content/fin/fin-help.md, docs/content/stack/zero-configuration.md
- Fix condition in exec that prevented executing a command in an arbitrary container
- Call `xargs` in a cross-platform compatible way in `fin cleanup` (#1076)
- Updated `fin` documentation
- Updated stock stacks description in docs
=> Release 1.12.3

docs/content/stack/images-versions.md
Fix typo in mariabd image names
=> Update mariadb image-names

bin/fin
Fixed issue where id wasn't being pulled if the letters ID appeared anywhere else on the screen. Changed the scope to look for lines that start with (space)id
=> Fixed issue with Acquia Pull DB

docs/content/service/cli/settings.md
=> Custom stack config URL fix

examples/.docksal/etc/ngrok/ngrok.yml
=> Fix issue with ngrok example file

docs/content/service/cli/startup.md, docs/content/stack/zero-configuration.md
=> Document the Startup.sh Script

stacks/services.yml
=> Adds DRUSH_OPTIONS_URI to the cli service.

bin/fin
Can be used as a wizard:
or as a one-liner:
```
fin project create --name=test --repo=https://github.com/docksal/drupal8.git
```
=> Allow creating projects from a custom git repo

docs/content/tools/xdebug.md
=> Fixed xdebug pages to use the correct files

docs/content/service/db/access.md
=> removes fin vm ip command from documentation and lists canonical IP

docs/content/fin/addons.md
=> adds wording about what an addon is, fixes minor typos

docs/content/fin/addons.md
=> adds additional wording for addon filelist to clarify it's only as needed

docs/content/stack/zero-configuration.md
Closes #1140 
@lmakarov You're new getting started section plus this minor update should close the issue.
=> adds pointer to new project setup for zero-config wizard experience

bin/fin, docs/content/stack/configuration-variables.md
=> Added DOCKSAL_CONFIRM_YES variable to allow auto-answering yes to all yes/no confirms

bin/fin
=> adds Drupal 8 BLT version for project create option

docs/content/tools/acquia-blt.md, docs/content/tools/composer.md
=> Adds Acquia BLT documentation

docs/content/stack/configuration-labels.md
Updates to recently added documentation page.
=> fixes minor wording, punctuation issues

bin/fin, docs/content/fin/fin.md, docs/content/troubleshooting/windows-smb.md, docs/content/use-cases/docker-modes.md, docs/content/use-cases/portable.md
=> Remove Babun mentions

tests/scripts/macos.sh, tests/scripts/project.sh
- Adds macos.sh for running bats tests on macos
- Fixes error in project.sh
=> Tests improvements

docs/content/stack/configuration-variables.md
I'm making a wild guess about some of these.
Closes #1082
=> adds scope of variable documentation

docs/content/use-cases/drupal-multisite.md
=> adds documentation on multisite setup

docs/content/tools/ide.md
Just two minor typos in the recently merge ide docs.
=> Fixes minor typos

docs/content/use-cases/extra-hosts.md
=> adds documentation on adding extra host information inside cli

docs/content/tools/wordpress.md
I know almost nothing of Wordpress. I have simply looked at the docs for Drupal and looked at the init scripts for the boilerplate Wordpress site. Please update/modify as necessary.
Closes #1144
=> adds wordpress settings doc

CHANGELOG.md, docs/content/getting-started/project-setup.md
Fixes typos, updates project create list, updates fin version in change log.
=> doc updates

stacks/overrides-ide.yml
=> Add IDE_PASSWORD var to IDE stack file

docs/content/core/system-dns.md
=> Change "two" to "to"

docs/content/core/overview.md, docs/content/core/system-ssh-agent.md
See https://github.com/docksal/docksal/issues/1239
=> Explain SSH agent proxy functionality

docs/content/use-cases/shared-cache-volumes.md
Use underscores (_) instead of dash (-)
=> Correct the creation of the named volumes

docs/content/tools/platformsh.md
=> Fixes broken link to fin pull page on the platform.sh page in the documentation.

bin/fin, docs/content/stack/configuration-variables.md
Fixes: https://github.com/docksal/docksal/issues/1009
Depends on: https://github.com/docksal/service-vhost-proxy/pull/63
=> Add projects autostart switch

bin/fin
=> Change uuid generation method

docs/content/core/volumes.md, docs/content/getting-started/setup.md
This is a hotfix (merge into master)
- Added a section about setting/checking `DOCKSAL_VOLUMES` (#1275, #1296)
- https://hotfix-docs--docs-docksal-io.netlify.com/core/volumes/#docksal-volumes
- Added warnings in install docs about Docker Desktop versions (#1268)
- https://hotfix-docs--docs-docksal-io.netlify.com/getting-started/setup/#install-macos-docker-for-mac
- https://hotfix-docs--docs-docksal-io.netlify.com/getting-started/setup/#install-windows-docker-for-windows
=> Hotfix: docs updates

bin/fin, stacks/services.yml
Fixes: https://github.com/docksal/docksal/issues/1288
=> Fix issue with starting cli from vhost-proxy and missing ssh agent socket

docs/content/use-cases/portainer.md
Updated the link for portainer: [http://portainer.docksal](http://portainer.docksal/)
=> portainer vs poratiner

docs/content/core/volumes.md
=> Fix the typo in volumes.md

docs/content/tools/platformsh.md
It should be either "a tool that allows you to manage your projects..." OR "a tool that allows for managing your projects..."
=> Fix English in platformsh.md

docs/content/core/system-vhost-proxy.md
=> adds documentation on adding a custom certificate for a project

bin/fin, docs/content/troubleshooting/common-issues.md
- Improved docker path access check
- Updated troubleshooting docs (+ [blog post](https://blog.docksal.io/nfs-access-issues-on-macos-10-15-catalina-75cd23606913))
Fixes #1350
=> Help users with NFS issues on macOS Catalina

docs/content/fin/addons.md, docs/content/tools/mkcert.md
=> docs mkcert addon

bin/fin
Adds the 3 new Drupal 9 boilerplate projects to the fin project create command.
=> updates projects to include Drupal 9 boilerplate projects

bin/fin
=> Adjusted approach to mounting ssh-agent socket in cli

README.md
I noticed you made some changes, so I reread this page and found a couple of minor changes needed.
=> fixes a few minor typos and wording

bin/fin, tests/db.bats
=> Prevent PTY allocation for mysql when no TTY is available

bin/fin
fixes #1408 
There was a mismatch of actual target repositories to the project create selection.
=> fixes target repositories to match project create selection

docs/content/fin/addons.md, docs/content/stack/configuration-variables.md, docs/content/troubleshooting/common-issues.md
- fin/addons
- stack/configuration-variables
- troubleshooting/common-issues
=> Fix internal linking in docs

bin/fin, docs/content/core/system-ssh-agent.md, docs/content/fin/fin-help.md
=> Fixed ssh-key help message + regenerated fin docs

docs/content/troubleshooting/common-issues.md
Windows section is still TBD
Closes #1348
=> updates troubleshooting docs on conflicting ports

docs/config.toml, docs/content/service/cli/settings.md, docs/content/tools/mkcert.md
This updates a few places where versions needed to be bumped.
=> Documentation minor update for versions

docs/content/tools/wordpress.md
=> documented wordpress multisite settings

docs/content/service/web/options.md
=> Fix Typo in service name described

docs/content/apps/_index.md, docs/content/apps/drupal.md, docs/content/apps/wordpress.md, docs/content/troubleshooting/_index.md
- Added "Applications" section
- Moved Drupal and Wordpress docs to a new section
- Added Wordpress HTTPS docs
=> Applications section + Wordpress HTTPS docs

bin/fin, docs/content/getting-started/setup.md
- Bump Docker versions
- docker v20.10.5
- docker-compose v1.28.5
- Docker Desktop v3.2.2 (61853)
- Bump VirtualBox v6.1.18
- Bump WSL Ubuntu v20.04 in docs
=> Bump dependency versions

docs/content/fin/fin-pull.md
Tiny update on the docs. Current version in master for Drush is now Drush 10.x.
=> Update drush links in doc for fin pull.

docs/layouts/partials/carbonads.html, docs/layouts/partials/search.html, docs/static/css/theme-docksal.css
- Added CarbonAds below search box
- Disabled AdSense via GTM (exclusivity requirement from CarbonAds)
Preview: https://deploy-preview-1472--docs-docksal-io.netlify.app/
=> CarbonAds in docs

docs/content/tools/xdebug.md, stacks/services.yml
Added content updates for configuring prior versions of docksal images with xdebug.
=> Added documentation for Xdebug 3

docs/content/core/volumes.md
Add warning to core volumes section on changing volume mount type.
closes #1461
=> adds warning for changing volume mount type

bin/fin, docs/content/tools/acquia-cli.md
This PR supercedes #1481 as it contains all the requested updates.
=> Update docs for Acquia CLI and add to top level commands

bin/fin
=> NFS fix for Docker Desktop (Virtualization Framework/M1) in macOS Big Sur

bin/fin
Adding a grep check of hostname in hosts file so that if `fin hosts add` is called multiple times, the hosts file won't contain multiple duplicates.
=> adds check for existing host name before adding to eliminate duplicates

docs/content/fin/addons.md
Several addons have been added since this list was last updated.
=> updates list of addons

stacks/overrides-xhprof.yml
Fixes xhprof service to work with newer wodby/xhprof images.
closes #1507
=> Issue 1507: Adding variable for 3.x wodby/xhprof.

docs/config.toml, docs/content/fin/fin-help.md
Updates versions in documentation for fin and Docksal
=> version docs

CONTRIBUTING.md, README.md, docs/config.toml, docs/content/troubleshooting/common-issues.md, docs/static/css/theme-docksal.css
Updating docs for community support on GitHub discussions
=> switches community support to GitHub discussions

docs/content/getting-started/setup.md
https://deploy-preview-1531--docs-docksal-io.netlify.app/getting-started/setup/#install-linux-other
=> adds Linux post installation note

bin/fin
=> Add sponsor prompt after update

bin/fin, docs/content/stack/configuration-variables.md, docs/content/use-cases/project-auto-start-stop.md
- Disable project auto-start by default
- Expanded docs around project auto start/stop features
This is a followup to #1592 discussion and #1009 feature request.
=> Disable project auto-start by default

docs/content/troubleshooting/common-issues.md
closes #1400 
This adds the documentation on how to allow all memory usage for composer.
=> adds documentation on composer memory issues

docs/config.toml, docs/content/sponsor.md
closes #1530 
You may be asking for information about the process, but I don't actually know what the process is myself. Here is a starting point for a sponsor page that includes information on how to contribute and what the contributions are used for (the best of my knowledge).
=> adds sponsor documentation

docs/content/troubleshooting/common-issues.md
This adds some additional bug fix steps [from Slack](https://drupal.slack.com/archives/C6GPEEEV8/p1613526619020000) regarding out of disk issues.
=> Add disk space issue to common issues.

stacks/stack-platformsh.yml
=> Fix stack-platformsh cli version.

bin/fin, docs/content/fin/fin-help.md, scripts/fin-help-generate.sh
- Reorganized and updated help sections in fin + misc updates in fin help
- Updated "fin help" docs script
- Included all current fin help subsections
- Changed Markdown slightly - rending code blocks in plain text instead of "randomly colored" text
- Regenerated fin help docs
Docs preview: https://deploy-preview-1620--docs-docksal-io.netlify.app/fin/fin-help/
Resolves #1619
=> fin help updates

stacks/stack-pantheon.yml
Closes https://github.com/docksal/docksal/issues/1626
=> Change DB image variable name in stack-pantheon.yml.

stacks/stack-default.yml
Quick fix updating the `stack-default` versions that were changed in #1631.
=> Update default stack comments

bin/fin
=> Include Docksal version in fin

.github/workflows/default.yaml
=> Fix release tag builds

docs/content/service/other/apache-solr.md
=> Added example on how to override solr service image

docs/content/troubleshooting/common-issues.md
Added notes to common issues about MDM services and how to debug when being used.
=> Added section in common issues for MDM troubleshooting

bin/fin, docs/content/use-cases/gitpod.md, stacks/overrides-gitpod.yml
Adds [Gitpod](https://gitpod.io) Integration
=> Gitpod Integration

bin/fin, docs/content/service/cli/settings.md, docs/content/stack/checking-configuration.md, docs/content/stack/images-versions.md, examples/.docksal/docksal.env, stacks/services.yml, stacks/stack-acquia.yml, stacks/stack-pantheon.yml, stacks/stack-platformsh.yml
- Switched apache service to `docksal/apache:2.4-2.5`
- Switched cli service to `docksal/cli` v3.2
=> Image updates

bin/fin
`DOCKSAL_VOLUMES` was incorrectly reset in `load_configuration()`.  This is a regression from https://github.com/docksal/docksal/pull/1551
=> Fix DOCKSAL_VOLUMES variable overide

docs/content/core/analytics.md, docs/content/core/system-ssh-agent.md, docs/content/service/db/access.md, docs/content/service/web/http-auth.md, docs/content/stack/configuration-variables.md, docs/content/stack/custom-configuration.md, docs/content/tools/acquia-cli.md, docs/content/tools/platformsh.md, docs/content/tools/terminus.md
=> updates documentation to use fin config set where appropriate

docs/content/getting-started/setup.md
=> Fix Ubuntu badge version

docs/content/fin/custom-commands.md, docs/content/fin/fin.md
=> docs python

bin/fin, tests/project.bats
- Reordered operations:
- "fin project start": dc create => (re)connect network => dc start
- "fin project stop": dc stop => disconnect & delete network
- Updated tests
Fixes #1693
=> Fix for network issues after project stop/restart

bin/fin
=> Fix stalled updates

bin/fin, docs/content/getting-started/project-setup.md
I noticed that the docs were out of date for the project create wizard. When running `fin project create` to get the output list, I noticed that the alignment was off for two of them and the "Enter your choice (0-15)" didn't match the 16 options that are given. These two items are fixed in this PR.
=> Updates docs and fin project create output

bin/fin
=> removes Drupal 9 from create project options

bin/fin
- Updated NFS exports for Docker Desktop with Virtualization Framework (macOS)
- Improved NFS diagnostics output in `sysinfo()`
Fixes #1800
=> Improve NFS exports configuration

bin/fin
- Compatibility with macOS 14.4 update (which broke "nfsd restart")
- Diagnostic enhancements
Fixes #1816. Closes #1821
=> Refactored NFS configuration

bin/fin, docs/content/fin/custom-commands.md, docs/content/fin/fin-help.md
=> Fix bash completion
